ready-to-run example for the periodic 2d hills case
xcompact3d/Incompact3d pull request #191
Opened 2023-05-31 14:08 UTC by slaizet

2023-05-31 16:11 UTC, pbartholomew08 requested changes

2023-05-31 16:11 UTC, pbartholomew08 commented on examples/2D-hill/input.i3d
> +cpg = F               ! if cpg=T, then re is friction Reynolds number
Does this work as a logical value? Does it not need to be `.true.` or `.false.`?

2023-05-31 16:11 UTC, pbartholomew08 commented on src/BC-Periodic-hill.f90
> +    !if (nrank==0) write(*,*) nrank,'UT',ut4,can
delete?

2023-06-01 05:37 UTC, mathrack commented on examples/2D-hill/input.i3d
> +cpg = F               ! if cpg=T, then re is friction Reynolds number
'F' or 'T' are valid values

2023-06-01 05:38 UTC, mathrack commented on src/BC-Periodic-hill.f90
> +
fprettify ?

2023-06-01 05:39 UTC, mathrack commented on src/BC-Periodic-hill.f90
> +  subroutine visu_hill_init(visu_initialised)
Add some extra lines between the subroutines

2023-06-01 08:34 UTC, slaizet commented on src/BC-Periodic-hill.f90
> +  subroutine visu_hill_init(visu_initialised)
done

2023-06-01 08:34 UTC, slaizet commented on src/BC-Periodic-hill.f90
> +    !if (nrank==0) write(*,*) nrank,'UT',ut4,can
done

2023-06-01 08:35 UTC, slaizet commented on src/BC-Periodic-hill.f90
> +
more or less done

2023-06-01 08:37 UTC, pbartholomew08 approved these changes
Looks good to me

2023-06-01 08:48 UTC, merged